### ISSUE TITLE
Auto merge should not proceed if approved reviews greater than minimum required but requested changes exist

### ISSUE THREAD

**Issue by Matticusau** [Matticusau/pr-helper#16]
## Bug Report

**Current Behavior**
The current logic is that the following conditions need to be met
1. All requested reviews are provided and minimum review is disabled
2. All provided reviews are approved and (reviews greater or equal to minimum count required or minimum count disabled)
3. Approved reviews is greater or equal to minimum count required (if enabled)

This could cause unexpected merger in the case where there are requested changes but others have approved the change as this would pass check 3

**To Reproduce**

With minimum review count = 1

1. Create a PR
2. As a reviewer request changes via a review
3. Another reviewer approve the change
4. Auto merge will happen

**Expected behavior/code**
We should expect that while there is a rejected review it does not process the auto merge

**GitHub Action Configuration (.yml, etc)**

```yaml
jobs:
  prhelper_job:
    runs-on: ubuntu-latest
    steps:
    - name: Run PR Helper
      id: runprhelper
      uses: Matticusau/pr-helper@v0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        enable-prmerge-automation: true
        enable-prcomment-automation: true
        enable-prlabel-automation: true
        enable-welcomemessage: true
        welcome-message: "Thanks for opening an issue! Make sure you've followed CONTRIBUTING.md."
        prmerge-requireallchecks: true
        prmerge-requirereviewcount: 1
        permerge-method: 'merge'
```
