### ISSUE TITLE
Support for key value lookup file on front matter reviewers

### ISSUE THREAD

**Issue by Matticusau** [Matticusau/pr-helper#23]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently in Jekyll like blog sites it is not mandatory to specify a GitHub username as the article Author or similar front matter value. It is common to use a friendly name which is then mapped to further details in an [author file](https://blog.sorryapp.com/blogging-with-jekyll/2014/02/06/adding-authors-to-your-jekyll-site.html).

**Describe the solution you'd like**
The solution should be to provide a path to a key:value YAML or JSON type file which is used to look up the GitHub username of the author. I prefer a YAML solution to match the configuration standard in GitHub Actions. I see two options:

1. Store a custom YAML file in the .github directory. This file could be in the format of 

```YAML
Author Name: githubusername
Author Name: githubusername
```

Or 

```YAML
Author Name:
  ghaccount: githubusername
Author Name:
  ghaccount: githubusername
```

2. **[Preferred option]** Support the use of the Jekyll Author file syntax. Similar to option 2 above. This could still be a path file in the .github directory or if it is a Jekyll blog then the `_data/authors.yml`. So adding an additional field to the author file for the GitHub UserName such as:

```YAML
# Author details.
Author Name:
    name: Author Name
    email: name@email.com
    web: http://twitter.com/account
    ghaccount: githubusername
Author Name:
    name: Author Name
    email: name@email.com
    web: http://twitter.com/account
    ghaccount: githubusername
```

**Describe alternatives you've considered**
Haven't found any alternative GitHub Actions to provide this functionality.

Alternatively we do not provide this functionality and simply continue with the current functionality which requires the GitHub account in the pages front matter. Which is not ideal as it duplicates the data needing to be maintained on each page if that is not already part of your Jekyll site.

**Teachability, Documentation, Adoption, Migration Strategy**
TBD
