### ISSUE TITLE
Auto merge not requiring qualify for auto merge label

### ISSUE THREAD

**Issue by Matticusau** [Matticusau/pr-helper#28]
## Bug Report

**Current Behavior**
Currently the auto merge workflow does not require that the auto merge qualifying label is set. That label is set during the workflow when it determines that the PR qualifies for auto merge or not. 

**To Reproduce**

1. Configure the path check to exclude some files
2. Create a PR that modifies files that pass the path check and others that do not pass the check
3. Notice that the PR will not have the qualifies for auto merge label assigned, however review the log files and the workflow will continue to try and process the PR for merge

**Expected behavior/code**
Additional check should be performed before merging to make sure it does qualify for auto merge, not that it is just ready to merge

**GitHub Action Configuration (.yml, etc)**

```yaml
with:
  enable-prmerge-automation: true
  prmerge-requireallchecks: true
  prmerge-requirereviewcount: 1
  prmerge-method: 'merge'
  prmerge-deletebranch: 'true'
  prmerge-deletebranch-config: ''
  prmerge-pathcheck: true
  prmerge-allowpaths: '{"any":["articles/**"]}'
  prlabel-default: 'pr-onhold'
  prlabel-ready: 'pr-ready'
  prlabel-onhold: 'pr-onhold'
  prlabel-reviewrequired: 'review-required'
  prlabel-automerge: 'qualifies-auto-merge'
```

**Possible Solution**
TBD

**Additional context/Screenshots**
Was discovered while investigating #27
