### ISSUE TITLE
Error when FrontMatter reviewer is enabled but file has no frontmatter

### ISSUE THREAD

**Issue by Matticusau** [Matticusau/pr-helper#30]
## Bug Report

**Current Behavior**
After enabling the frontmatter reviewer assignment and modifying a file that has no frontmatter it generates the following error

![image](https://user-images.githubusercontent.com/11083642/88505177-19df1980-d01a-11ea-8977-898f107eed90.png)

**To Reproduce**

1. Create a PR that modifies files with no frontmatter

**Expected behavior/code**
Should not generate an error for files without frontmatter and should not assign a reviewer

**GitHub Action Configuration (.yml, etc)**

```yaml
with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        enable-prmerge-automation: true
        enable-prcomment-automation: true
        enable-prlabel-automation: true
        enable-prreviewer-frontmatter: true
        enable-welcomemessage: true
        welcome-message: "Thanks for opening an issue! Make sure you've followed CONTRIBUTING.md."
        prmerge-requireallchecks: true
        prmerge-requirereviewcount: -1
        prmerge-pathcheck: true
        prmerge-method: 'merge'
        prmerge-deletebranch: true
        prmerge-deletebranch-config: '{"deny":["dev", "main"]}'
        prmerge-allowpaths: '{"any":["docs/**","assets/**"]}'
        prreviewer-authorkey: 'author'
        prreviewer-githubuserfromauthorfile: true
        prreviewer-authorfilepath: '_data/authors.yaml'
        prlabel-default: 'pr-onhold'
        prlabel-ready: 'pr-ready'
        prlabel-onhold: 'pr-onhold'
        prlabel-reviewrequired: 'review-required'
        prlabel-automerge: 'auto-merge'
```

**Possible Solution**
TBA

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/11083642/88505182-1cda0a00-d01a-11ea-828e-d80ff7f665c6.png)
